# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeExpandImportedTargets.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckCSourceCompiles.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckFunctionExists.c\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckFunctionExists.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckIncludeFile.c.in\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckIncludeFile.cmake\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckTypeSize.c.in\
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckTypeSize.cmake\
/Users/minh/projects/iqtree-cmake/CMakeFiles/CheckTypeSize/OFF64_T.c\
/Users/minh/projects/iqtree-cmake/zlib-1.2.7/CMakeLists.txt\
/Users/minh/projects/iqtree-cmake/zlib-1.2.7/zconf.h.cmakein\
/Users/minh/projects/iqtree-cmake/zlib-1.2.7/zlib.pc.cmakein
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/minh/projects/iqtree-cmake -B/Users/minh/projects/iqtree-cmake
